---

- name: "Install CloudWatch Log Agent (Amazon)"
  yum:
    name: awslogs
    state: present
  register: yum_result
  ignore_errors: true

- block:
  - name: "Get ec2 facts"
    action: ec2_metadata_facts

  - name: "Create /etc/awslogs"
    file:
      path: /etc/awslogs
      state: directory
      mode: 755