---

- name: "Set region for Cloudwatch endpoint"
  template:
    src: templates/etc/aws.conf.j2
    dest: /var/awslogs/etc/aws.conf
    owner: root
    group: root
    mode: 0600

- name: "Restart awslogs service."
  service:
    name: awslogsd
    state: restarted
    enabled: yes